# Generated by Django 3.1 on 2020-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200819_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coast',
            name='method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
