# Generated by Django 3.1 on 2020-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_order_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_work',
        ),
        migrations.AddField(
            model_name='order',
            name='service_work',
            field=models.ManyToManyField(blank=True, to='main.Service'),
        ),
    ]
